# Practical 6
#### Miarisoa Elalie Rasamimanana

In [142]:
import numpy as np

**Exercise 1:**

Create a NumPy array of integers from 1 to 10.

In [143]:
array_int = np.arange(1,11)
array_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Exercise 2:**

Create a 3x3 NumPy array filled with zeros.

In [144]:
array = np.zeros((3,3),dtype=int)
array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [145]:
array = np.zeros((3,3),dtype=np.int16)
array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [146]:
array.dtype

dtype('int16')

**Exercise 3:**

Create a NumPy array of 10 evenly spaced numbers between 0 and 5.



In [147]:
array = np.linspace(0,5,10)
array


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [148]:
array = np.linspace(0,5,10,endpoint=False)
array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

**Exercise 4:**

Create a 5x5 identity matrix using NumPy.

In [9]:
array=np.eye(5,5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Exercise 5:**

Create a 4x4 matrix with random values between 0 and 1.

In [10]:
array = np.random.rand(4,4)
array

array([[0.34003623, 0.96717781, 0.64502738, 0.97250317],
       [0.50314135, 0.22106566, 0.33098724, 0.72249473],
       [0.54734921, 0.2650868 , 0.15836681, 0.13865609],
       [0.2539998 , 0.91268079, 0.89377034, 0.58710152]])

In [11]:
np.random.seed(0)

In [12]:
array = np.random.random((4,4))
array

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

**Exercise 6:**

Find the shape of a NumPy array.

In [13]:
array.shape

(4, 4)

**Exercise 7:**

Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [14]:
array = np.arange(16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
array.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Exercise 8:**

Find the data type of the elements in a NumPy array.

In [16]:
array.dtype

dtype('int64')

**Exercise 9:**

Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [17]:
array = np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
even_array = [x for x in array if x%2==0]
print(even_array, end=',')

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100],

In [19]:
array = np.arange(2,101,2)
array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Exercise 10:**

Generate a 6x6 matrix of random integers between 10 and 50.

In [150]:
array = np.random.randint(10,50, size=(6,6))
array

array([[44, 42, 45, 49, 37, 20],
       [14, 27, 13, 47, 40, 33],
       [39, 48, 40, 21, 12, 39],
       [17, 19, 33, 10, 27, 31],
       [40, 36, 25, 27, 20, 27],
       [13, 49, 19, 39, 13, 17]])

**Exercise 11:**

Slice a 2D NumPy array to extract a submatrix.

In [151]:
sub = array[0:2, 1:3]
sub

array([[42, 45],
       [27, 13]])

**Exercise 12:**

Calculate the sum of all elements in a NumPy array.

In [23]:
somme = np.sum(array)
somme

1061

**Exercise 13:**

Calculate the mean, median, and standard deviation of a NumPy array.

In [24]:
mean = np.mean(array)
mean

29.47222222222222

In [25]:
sort_array = np.sort(array)
length = len(sort_array)
if length %2==0:
    median = length/2
    print(median)
else:
    median = (length+1)/2
    print(median)

3.0


In [26]:
standard = np.std(array,ddof=0)
standard

13.198245066655874

**Exercise 14:**

Find the maximum and minimum values in a NumPy array.

In [27]:
maxm = np.max(array)
minm=np.min(array)
maxm,minm

(49, 10)

**Exercise 15:**

Create a NumPy array of 20 random integers and find the index of the maximum value.

In [28]:
array = np.random.randint(20, size=20)
array

array([ 6, 11, 14, 18,  0, 14,  3, 12, 10, 11,  4,  6,  4, 15,  3, 12,  4,
        8, 14, 15])

In [29]:
maxvalue = np.argmax(array)
print(maxvalue)

3


**Exercise 16:**

Create a NumPy array and reverse its elements.

In [30]:
array = np.random.randint(9, size=(3,3))
array

array([[4, 3, 7],
       [5, 5, 0],
       [1, 5, 3]])

In [31]:
array[::-1]

array([[1, 5, 3],
       [5, 5, 0],
       [4, 3, 7]])

**Exercise 17:**

Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.



In [32]:
array1 = np.random.randint(9, size=(3,3))
array2 = np.random.randint(9, size=(3,3))
array1,array2

(array([[0, 5, 0],
        [1, 2, 4],
        [2, 0, 3]]),
 array([[2, 0, 7],
        [5, 0, 2],
        [7, 2, 2]]))

In [33]:
np.multiply(array1,array2)

array([[ 0,  0,  0],
       [ 5,  0,  8],
       [14,  0,  6]])

**Exercise 18:**

Create a diagonal matrix from a given 1D array.

In [152]:
array = np.array([1,2,3])
np.diag(array)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

**Exercise 19:**

Perform matrix multiplication on two 2D NumPy arrays.

In [35]:
np.dot(array1, array2)

array([[25,  0, 10],
       [40,  8, 19],
       [25,  6, 20]])

**Exercise 20:**

Flatten a 2D NumPy array into a 1D array.

In [36]:
array1.flatten()

array([0, 5, 0, 1, 2, 4, 2, 0, 3])

**Exercise 21:**

Stack two NumPy arrays vertically.

In [38]:
np.vstack((array1,array2))

array([[0, 5, 0],
       [1, 2, 4],
       [2, 0, 3],
       [2, 0, 7],
       [5, 0, 2],
       [7, 2, 2]])

**Exercise 22:**

Stack two NumPy arrays horizontally.



In [39]:
np.hstack((array1,array2))

array([[0, 5, 0, 2, 0, 7],
       [1, 2, 4, 5, 0, 2],
       [2, 0, 3, 7, 2, 2]])

**Exercise 23:**

Split a NumPy array into multiple sub-arrays.

In [41]:
np.split(array1,3)

[array([[0, 5, 0]]), array([[1, 2, 4]]), array([[2, 0, 3]])]

**Exercise 24:**

Generate a random NumPy array and round each element to two decimal places.

In [42]:
np.round(array1,2)

array([[0, 5, 0],
       [1, 2, 4],
       [2, 0, 3]])

**Exercise 25:**

Find the unique elements of a NumPy array.

In [43]:
array = np.array([ 0,  3,  4,  0,  7,  8, 10, 11, 0, 14, 15, 3, 1])

In [44]:
np.unique(array)

array([ 0,  1,  3,  4,  7,  8, 10, 11, 14, 15])

**Exercise 26:**

Replace all elements in a NumPy array that are less than a specific value with that value.

In [45]:
spec_value=4
array[array<spec_value]=spec_value
array

array([ 4,  4,  4,  4,  7,  8, 10, 11,  4, 14, 15,  4,  4])

**Exercise 27:**

Find the cumulative sum of the elements in a NumPy array.

In [47]:
np.cumsum(array)

array([ 4,  8, 12, 16, 23, 31, 41, 52, 56, 70, 85, 89, 93])

**Exercise 28:**

Create a NumPy array and find the number of non-zero elements in it.



In [48]:
np.count_nonzero(array)

13

**Exercise 29:**

Create a NumPy array of random integers and sort it in ascending order.



In [49]:
array = np.random.randint(0,20, size=(3,3))
np.sort(array)

array([[ 3,  3, 18],
       [ 3, 14, 17],
       [ 9, 14, 18]])

**Exercise 30:**

Find the row-wise and column-wise sum of a 3x3 matrix.



In [50]:
row_wise = np.sum(array1,axis=1)
row_wise

array([5, 7, 5])

In [51]:
column_wise = np.sum(array1,axis=0)
column_wise

array([3, 7, 7])

**Exercise 31:**

Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1)

In [57]:
array = np.random.rand(5)
(array - np.min(array)) / (np.max(array) - np.min(array))

array([0.07438848, 0.72010309, 0.        , 1.        , 0.48570378])

**Exercise 32:**

Create two NumPy arrays and find the dot product.

In [58]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
np.dot(array1, array2)

32

**Exercise 33:**

Find the trace of a square NumPy matrix.



In [64]:
array = np.random.randint(0,20, size=(3,3))
array

array([[11,  6, 15],
       [ 1, 12,  3],
       [18, 15,  3]])

In [65]:
np.trace(array)

26

**Exercise 34:**

Create a 2D array and swap two rows.

In [66]:
array[[0, 2]] = array[[2, 0]]
array

array([[18, 15,  3],
       [ 1, 12,  3],
       [11,  6, 15]])

**Exercise 35:**

Create a 1D NumPy array and convert it into a column vector.

In [67]:
array = np.random.rand(5)

In [68]:
array[:, np.newaxis]

array([[0.36756187],
       [0.43586493],
       [0.89192336],
       [0.80619399],
       [0.70388858]])

**Exercise 36:**

Find the determinant of a 3x3 matrix.

In [72]:
array = np.random.randint(0,20, size=(3,3))
array

array([[ 3, 14, 18],
       [12,  3,  9],
       [10, 13,  7]])

In [73]:
np.linalg.det(array)

2063.9999999999986

**Exercise 37:**

Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [74]:
array = np.random.randint(0,9, size=(2,2))
array

array([[7, 5],
       [1, 2]])

In [76]:
eigenvalue, eigenvector=np.linalg.eig(array)
eigenvalue

array([7.85410197, 1.14589803])

In [77]:
eigenvector

array([[ 0.98572192, -0.6494574 ],
       [ 0.16838141,  0.76039797]])

**Exercise 38:**

Solve a system of linear equations using NumPy.

In [79]:
A = np.array([[2, 3],[4, 5]])
B = np.array([6, 7])
np.linalg.solve(A, B)

array([-4.5,  5. ])

**Exercise 39:**

Add Gaussian noise to a NumPy array.

In [81]:
array = np.array([1, 2, 3, 4, 5])
mean = 0
std_dev = 0.1
np.random.normal(mean, std_dev, array.shape)

array([-0.06743327,  0.00318306, -0.06358461,  0.06764333,  0.05765908])

**Exercise 40:**

Create a 4x4 matrix and extract the diagonal elements.

In [82]:
array = np.random.randint(0,20, size=(3,3))
array

array([[ 8,  1, 17],
       [16,  3,  8],
       [ 4, 16,  3]])

In [83]:
np.diagonal(array)

array([8, 3, 3])

**Exercise 41:**

Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [89]:
array = np.random.randint(0,100,100)

In [90]:
np.clip(array, 10, 50)

array([50, 50, 50, 10, 12, 50, 37, 39, 32, 33, 26, 50, 50, 50, 50, 50, 20,
       50, 28, 50, 18, 25, 24, 39, 28, 24, 18, 50, 44, 50, 45, 50, 10, 10,
       50, 10, 50, 50, 50, 50, 19, 34, 50, 20, 43, 10, 50, 50, 12, 15, 33,
       23, 12, 10, 38, 10, 10, 10, 10, 38, 50, 50, 50, 50, 10, 50, 29, 10,
       50, 10, 50, 50, 43, 50, 50, 50, 47, 50, 21, 18, 50, 13, 50, 50, 50,
       10, 48, 40, 26, 30, 10, 15, 50, 37, 50, 50, 50, 50, 32, 50])

**Exercise 42:**

Create a 2D NumPy array and replace all negative values with zero.

In [92]:
array = np.random.randint(-10,10, size=(3,3))
array

array([[  0,   2, -10],
       [ -3,   9,  -5],
       [ -6,   9,  -6]])

In [93]:
array[array < 0] = 0
array

array([[0, 2, 0],
       [0, 9, 0],
       [0, 9, 0]])

**Exercise 43:**

Find the inner and outer products of two NumPy arrays.

In [97]:
array1 = np.random.randint(9, size=(3,3))
array2 = np.random.randint(9, size=(3,3))
array1,array2

(array([[0, 1, 5],
        [6, 1, 4],
        [0, 4, 7]]),
 array([[7, 7, 6],
        [2, 6, 0],
        [2, 7, 7]]))

In [98]:
inner_product = np.dot(array1, array2)
inner_product

array([[12, 41, 35],
       [52, 76, 64],
       [22, 73, 49]])

In [99]:
outer_product = np.outer(array1, array2)
outer_product

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  7,  6,  2,  6,  0,  2,  7,  7],
       [35, 35, 30, 10, 30,  0, 10, 35, 35],
       [42, 42, 36, 12, 36,  0, 12, 42, 42],
       [ 7,  7,  6,  2,  6,  0,  2,  7,  7],
       [28, 28, 24,  8, 24,  0,  8, 28, 28],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [28, 28, 24,  8, 24,  0,  8, 28, 28],
       [49, 49, 42, 14, 42,  0, 14, 49, 49]])

**Exercise 44:**

Calculate the pairwise distances between points in a NumPy array.

**Exercise 45:**

Create a structured NumPy array with fields for name, age, and height.

In [105]:
array = np.array([('Alice', 25, 1.68),('Bob', 30, 1.75),('Charlie', 22, 1.80)])
array

array([['Alice', '25', '1.68'],
       ['Bob', '30', '1.75'],
       ['Charlie', '22', '1.8']], dtype='<U32')

**Exercise 46:**

Create a 5x5 matrix of random integers and count the occurrences of each unique value.

In [109]:
array = np.random.randint(0, 10, size=(5, 5))
unique, counts = np.unique(array, return_counts=True)
unique

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
counts

array([4, 3, 3, 5, 3, 3, 1, 2, 1])

**Exercise 47:**

Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

Exercise 48:

Create a NumPy array of random integers and check if any of the values are greater than 50.

**Exercise 52:**

Create a random NumPy array and compute its variance and standard deviation.

In [119]:
array = np.random.randint(-10,10, size=(3,3))
array

array([[ 8,  1,  9],
       [ 7,  5, -7],
       [ 0,  4,  5]])

In [120]:
variance = np.var(array)
variance

21.80246913580247

In [121]:
std_deviation = np.std(array)
std_deviation

4.669311419877932

**Exercise 53:**

Create a 2D NumPy array and find the indices of the maximum values along each axis.

In [124]:
max_col = np.argmax(array, axis=0)
max_row = np.argmax(array, axis=1)
max_col,max_row

(array([0, 1, 0]), array([2, 0, 2]))

**Exercise 54:**

Compute the inverse of a 2x2 NumPy matrix.

In [125]:
array = np.random.randint(0,9, size=(2,2))
array

array([[1, 7],
       [2, 1]])

In [127]:
inverse = np.linalg.inv(array)
inverse

array([[-0.07692308,  0.53846154],
       [ 0.15384615, -0.07692308]])

**Exercise 55:**

Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

In [128]:
mean = np.mean(array)
std_dev = np.std(array)
standardized_array = (array - mean) / std_dev
standardized_array

array([[-0.70352647,  1.70856429],
       [-0.30151134, -0.70352647]])

**Exercise 56:**

Perform element-wise addition and subtraction on two NumPy arrays.

In [138]:
array1 = np.random.randint(9, size=(3,3))
array2 = np.random.randint(9, size=(3,3))
array1, array2

(array([[1, 1, 1],
        [7, 0, 0],
        [2, 1, 4]]),
 array([[6, 0, 6],
        [6, 2, 8],
        [6, 6, 5]]))

In [139]:
addition = array1 + array2
addition

array([[ 7,  1,  7],
       [13,  2,  8],
       [ 8,  7,  9]])

In [141]:
subtraction = array1 - array2
subtraction

array([[-5,  1, -5],
       [ 1, -2, -8],
       [-4, -5, -1]])

**Exercise 57:**

Create a NumPy array of random values and find the maximum element's index.

In [133]:
array = np.random.randint(0,10,5)
array

array([2, 0, 2, 2, 9])

In [134]:
max_index = np.argmax(array)
max_index

4

**Exercise 58:**

Create a 3x3 NumPy array and rotate it by 90 degrees.

In [136]:
array = np.random.randint(-10,10, size=(3,3))
array

array([[ 2,  1,  2],
       [ 5,  1,  3],
       [ 4,  8, -6]])

In [137]:
rotated = np.rot90(array)
rotated

array([[ 2,  3, -6],
       [ 1,  1,  8],
       [ 2,  5,  4]])